"""empty message

Revision ID: 3275a39ddad4
Revises: a60f895ad51e
Create Date: 2019-08-17 11:34:15.072153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3275a39ddad4'
down_revision = 'a60f895ad51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('id_sub_area', sa.Integer(), nullable=True))
    op.drop_column('organization', 'sector')
    op.drop_column('sub_area', 'id_attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_area', sa.Column('id_attendance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('sector', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('organization', 'id_sub_area')
    # ### end Alembic commands ###
