"""empty message

Revision ID: 3663e9f9c8f0
Revises: 92cab9e22d6b
Create Date: 2019-07-16 23:42:16.445791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3663e9f9c8f0'
down_revision = '92cab9e22d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sector', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('super_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'super_admin')
    op.drop_column('user', 'sector')
    # ### end Alembic commands ###
